# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_plugin:
    docker:
        - image: circleci/node:10
    working_directory: ~/grafana-discrete-panel
    steps:
        - checkout
        - run:
            name: Run Build
            command: |
              npm install
              npm run build
        - persist_to_workspace:
            root: .
            paths:
            - dist

  release:
    docker:
      - image: cibuilds/github:0.12

    working_directory: ~/grafana-discrete-panel

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "23:c7:6e:08:8d:bc:50:14:95:77:1a:f8:d3:59:6f:5f"
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            PLUGIN_NAME=grafana-discrete-panel
            apk add --update --no-cache jq
            VERSION=`cat dist/plugin.json|jq '.info.version'| sed s/\"//g`
            ls -al
            git config user.email "rozetko@corpglory.com"
            git config user.name "CircleCI"
            git checkout -b release-${VERSION}
            git add --force dist/
            git commit -m "automated release $VERSION [skip ci]"
            git push -f origin release-${VERSION}
            git tag -f v${VERSION}
            git push -f origin v${VERSION}
            ghr \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -n "${PLUGIN_NAME} v${VERSION}" \
              -delete \
              v${VERSION}

workflows:
  version: 2
  plugin_workflow:
    jobs:
    - build_plugin
    - release:
        requires: 
          - build_plugin
